### ISSUE TITLE
"how live" fails if there re spaces in the file path for docker exec

### ISSUE THREAD

**Issue by hardevsanghera** [shuguet/how#1]
Hi Sylvain,

I got a "docker: invalid reference format: repository name must be lowercase." message when running "how live" - this fix resolved the issue: https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase

so in the how script

    exec docker run --rm -it \
                    -v $(pwd):/wd \
                    -p 8000:8000 $DOCKER_IMAGE:$VERSION "$@"

becomes

    exec docker run --rm -it \
                    -v "$(pwd):/wd" \           #added quotes
                    -p 8000:8000 $DOCKER_IMAGE:$VERSION "$@"

Thanks.

**Comment by shuguet** [comment]
Thank you Hardev, I included your fix in the code.
Hope you like the tool!
